#!/usr/bin/env python3

import skilstak.colors as c
from random import randint
from time import sleep

display = {
    1 : c.green + "1" + c.x,
    2 : c.red + "2" + c.x,
    3 : c.blue + "3" + c.x,
    4 : c.yellow + "4" + c.x,
}

sequence = []

delay = 0.2

f = open('highscore', 'r+')

highscore = f.read()

def welcome():
    print(c.clear + c.red + "Welcome to the Simon game!" + c.x)
    print(" (Press Enter to Begin) ", end='')
    input()

def pick():
    return randint(1,4)

def pick_colored():
    global display
    return display[pick()]

def add_to_sequence():
    global sequence
    sequence.append(pick())

def display_sequence():
    global sequence
    global display
    global delay
    for num in sequence:
        print(display[num], end=' ', flush=True)
        sleep(delay)
    sleep(1)
    print(c.clear)

def gameover():
    print(c.red + 'Game Over! You got ' + str(len(sequence)) + '!' + c.x)
    sleep(2)
    print(c.clear)
    exit()

def user_input():
    print(c.blue,end="")
    user_in = input()
    print(c.x,end="")
    user_in = list(map(int, user_in))
    global user_in

def check():
    if user_in == sequence:
         print(c.green + 'Good! You got ' + str(len(sequence)) + '!' + c.x)
         sleep(1)
         print(c.clear)
    else:
         gameover()

if __name__ == '__main__':
    welcome()
    user_input()
    while True:
        add_to_sequence()
        display_sequence()
        user_input()
        check()
    
